### ISSUE TITLE
Please UPDATE

### ISSUE THREAD

**Issue by ychoucha** [royopa/fpdf-symfony2#1]
Hello,

please update u bundle :)

**Comment by FTwex** [comment]
Hi,
if you want, i've forked this repo to provide updates
[https://github.com/FTwex/fpdf-symfony2](url)

**Comment by Dntfreitas** [comment]
Hi all,

Is this a still maintained bundle?

Thank you in advance!

**Comment by royopa** [comment]
Hi Diogo!

Yes!

Regards

**Comment by royopa** [comment]
@ychoucha @Dntfreitas @FTwex I have updated to last version fpdf and fpdi
