### ISSUE TITLE
External scripts

### ISSUE THREAD

**Issue by NodokaMurmevent** [royopa/fpdf-symfony2#2]
It's possible to add one script listed here  [http://www.fpdf.org/en/script/](http://www.fpdf.org/en/script/) ?
If yes who it's can be done ? i need tu use "PDF_Label"

Thanks for any help

**Comment by NodokaMurmevent** [comment]
i have found a solution it's dirty but it's work, just add complete path to the php file in the controller. 
Exemple : `require_once '/home/user/../AdminBundle/Controller/PDF_label.php';`
just before the `class namecontroller {`

**Comment by royopa** [comment]
@NodokaMurmevent I will close this issue, because you found the solution! Regards
