### ISSUE TITLE
FPDI package upgrade

### ISSUE THREAD

**Issue by viher3** [royopa/fpdf-symfony2#4]
You need to upgrade FPDI library version to latest. Because with some PDF format files returns errors and it is not working well.

```
"setasign/fpdf": "1.8.*",
"setasign/fpdi": "^2.0",
```

https://github.com/Setasign/FPDI

**Comment by royopa** [comment]
Hi @viher3 Thanks for the message!
This project is opened for collaboration. Could you do it and send a pull request?
I appreciate if you send this PR.
Thanks so much

**Comment by royopa** [comment]
Done @viher3!
https://github.com/royopa/fpdf-symfony2/commit/c013516926727b8b71d9c378f9bd2fda17f17c07

**Comment by viher3** [comment]
Thanks mate!
